name: Build image and push to dockerhub registry

on:
  push:
    branches:
      - main


jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run:
          make build

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Push image:latest to Dockerhub Registry
        run:
          docker push cyberdojo/rubocop